### ISSUE TITLE
Draft public documentation

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-opentelemetry-integration-java#14]
IN addition to the repo README, we need to create public documentation for https://docs.newrelic.com/.

See draft [here](https://docs.google.com/document/d/1kEQUopDPYSDHVoCiGZUBaaP7LmVu_Ah_B2N4V3tTFDk/edit?usp=sharing )

**Comment by jack-berg** [comment]
Looks like I created a copy of this as a result of today's refinement session. I'm going to close this issue in favor of [this](https://github.com/newrelic/newrelic-opentelemetry-integration-java/issues/14).
