### ISSUE TITLE
Figure out and document how this project will be supported

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-opentelemetry-integration-java#15]
We need to establish what the expectations are for the GTS org when it comes to supporting this and make sure that they have the proper training/resources to do so.

**Comment by kford-newrelic** [comment]
Engineering team will host a training session via support collaboration meeting, then this issue will be closed.

**Comment by jasonjkeller** [comment]
I attended support collab today and gave them a demo/overview of the OTel agent bundle and our current strategy around OTel (we recorded the session so that others in support who weren’t present can self serve).
