### ISSUE TITLE
Update the (Oscariffic) open-telemetry-sample-test-app to support the latest in OTel

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-opentelemetry-integration-java#2]
The [(Oscariffic) open-telemetry-sample-test-app](https://source.datanerd.us/java-agent/open-telemetry-sample-app) will be a primary tool for testing OTel based instrumentation. Let's update it to support the latest in OTel:

- Just snapshots, current otel auto agent. 
- Update manual instrumentation if need be.
- Look and see if there is more functionality that we want to add to our test app.
- Make sure we have spans more than one level deep.
- Test published newrelic-opentelemetry-integration-java bundle artifact in demo app
- Let's also change the account where this app is reporting to when deployed on [Grand Central](https://grand-central.datanerd.us/#/projects/3116) so that it's not getting rate limited due to the insane traffic on account 1.

**Comment by gfuller1** [comment]
We are deciding to close this issue because we already have example apps for the integration bundle and oscariffic would require a large effort to update.
