### ISSUE TITLE
Implement config for integration

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-opentelemetry-integration-java#4]
While the ultimate syntax may change, the NR OTel agent should support the following config:

- newrelic.api.key
- newrelic.service.name
- newrelic.trace.uri.override
- newrelic.metric.uri.override
- newrelic.enable.audit.logging

**Comment by Stephan202** [comment]
@jasonjkeller are there still plans to merge your changes to support environment variables? I'm asking because using environment variables it's possible (easier?) to inject the New Relic Insights key based on a Kubernetes Secret. :)
