### ISSUE TITLE
Archive the OTel Integration bundle

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-opentelemetry-integration-java#50]
Per comments on https://github.com/newrelic/newrelic-opentelemetry-integration-java/issues/47#, we will archive this repository.

Note: we do not anticipate this to be the case, but in the future, we may choose to create another different bundle that includes the Java OTel agent plus some other NR-specific functionality. This would only be the case if we felt that it did not also provide value to the general community.

Aha! Link: https://newrelic.aha.io/features/JAVA-240

**Comment by jasonjkeller** [comment]
Project has been archived: https://github.com/newrelic/newrelic-opentelemetry-integration-java/blob/main/README.md#archival-notice
